services:
  db:
    image: postgres:16.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PG_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
  kroki: # see https://docs.kroki.io/kroki/setup/use-docker-or-podman/#_run_multiple_kroki_containers_together
    image: yuzutech/kroki:0.24.1
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid
    ports:
      - "8123:8000"
  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8124" # this port is consumed by kroki only (and not by cutover-tool directly)
volumes:
  db-data:
